services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-vol:/prometheus
    networks:
      - prometheus-network
    healthcheck:
      test: ['CMD', 'wget', 'http://localhost:9090']
      interval: 10s
      timeout: 15s
      retries: 10
      start_period: 40s

  grafana:
    depends_on:
      prometheus:
        condition: service_healthy
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SERVER_DOMAIN=${GF_SERVER_DOMAIN}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana-data-vol:/var/lib/grafana
      - grafana-home-vol:/usr/share/grafana
      - grafana-config-vol:/etc/grafana
    networks:
      - prometheus-network

volumes:
  prometheus-vol:
  grafana-data-vol:
  grafana-home-vol:
  grafana-config-vol:

networks:
  prometheus-network:
    name: prometheus-network
    external: true
