services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-vol:/prometheus
    networks:
      - prometheus-network

  grafana:
    depends_on:
      - prometheus
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SERVER_DOMAIN=${GF_SERVER_DOMAIN}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana-data-vol:/var/lib/grafana
      - grafana-home-vol:/usr/share/grafana
      - grafana-config-vol:/etc/grafana
    networks:
      - prometheus-network

volumes:
  prometheus-vol:
  grafana-data-vol:
  grafana-home-vol:
  grafana-config-vol:

networks:
  prometheus-network:
    name: prometheus-network
    external: true
