global:
  evaluation_interval: 30s

scrape_configs:
  - job_name: node
    scrape_interval: 15s
    static_configs:
      - targets:
          [
            'node-host-ip-address:4000',
            'node-host-ip-address:4000',
            'node-host-ip-address:4000',
          ]
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          [
            'cadvisor-$(hostname1):8080',
            'cadvisor-$(hostname2):8080',
            'cadvisor-$(hostname3):8080',
          ]
