global:
  scrape_interval: 5s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'cadvisor'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          [
            'cadvisor-$(hostname1):8080',
            'cadvisor-$(hostname2):8080',
            'cadvisor-$(hostname3):8080',
          ]
